language: node_js

node_js:
  - "node"
  - "14"
  - "12"

os:
  - windows

before_install:
  - /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/Common7/Tools/VsDevCmd.bat;
  - which cmake;
  - wget -q https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.0/bin/hdf5-1.12.0-Std-win10_64-vs15.zip -O /tmp/hdf5-1.12.0-Std-win10_64-vs15.zip;
  - unzip -q /tmp/hdf5-1.12.0-Std-win10_64-vs15.zip;
  - ls ./hdf;
  - mkdir -p `pwd`/hdf5-1.12.0/dist;
  - cd hdf;
  - echo `pwd`;
  - readlink -f HDF5-1.12.0-win64.msi;
  - ls -lastr `pwd`/HDF5-1.12.0-win64.msi;
  - powershell "Start-Process -FilePath msiexec.exe -Wait -ArgumentList '/i `pwd`/HDF5-1.10.5-win64.msi /qn'"
  - cd ..;
  - ls "C:/Program Files/";